// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcjbcbmvkajwnsuzhefh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjamJjYm12a2Fqd25zdXpoZWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzMDY0NzIsImV4cCI6MjA5MTg4MjQ3Mn0.OXBWU3OIYlgWif88uR1r5uVnldv22YpjsmyhgEoHaEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});